/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baithi;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.security.MessageDigest;
import java.security.spec.KeySpec;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.DESedeKeySpec;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class FormEncrypt extends javax.swing.JFrame {

    /**
     * Creates new form FormEncrypt
     */
    private static final String UNICODE_FORMAT="UTF8";
    public static final String DESEDE_ENCRYPTION_SCHEME="DESede";
    private KeySpec myKeySpec;
    private SecretKeyFactory mySecretKeyFactory;
    private Cipher cipher;
    byte[] keyAsBytes;
    private String myEncryptionKey;
    private String myEncryptionScheme;
    private String myDecryptionKey;
    private String myDecryptionScheme;
    SecretKey key;
    public FormEncrypt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtM1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtK1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtE1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtM2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtN1 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtH2 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtM3 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtN2 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtK3 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtE3 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnMaHoaM1 = new javax.swing.JButton();
        btnNoiChuoiN1 = new javax.swing.JButton();
        btnBamChuoiN1 = new javax.swing.JButton();
        btnNoiChuoiN2 = new javax.swing.JButton();
        btnMaHoaN2 = new javax.swing.JButton();
        btnLuuFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FROM ENCRYPT");

        jLabel2.setText("Message(M1)");

        txtM1.setColumns(20);
        txtM1.setRows(5);
        jScrollPane1.setViewportView(txtM1);

        txtK1.setColumns(20);
        txtK1.setRows(5);
        jScrollPane2.setViewportView(txtK1);

        txtE1.setColumns(20);
        txtE1.setRows(5);
        jScrollPane3.setViewportView(txtE1);

        txtM2.setColumns(20);
        txtM2.setRows(5);
        jScrollPane4.setViewportView(txtM2);

        txtN1.setColumns(20);
        txtN1.setRows(5);
        jScrollPane5.setViewportView(txtN1);

        txtH2.setColumns(20);
        txtH2.setRows(5);
        jScrollPane6.setViewportView(txtH2);

        txtM3.setColumns(20);
        txtM3.setRows(5);
        jScrollPane7.setViewportView(txtM3);

        txtN2.setColumns(20);
        txtN2.setRows(5);
        jScrollPane8.setViewportView(txtN2);

        txtK3.setColumns(20);
        txtK3.setRows(5);
        jScrollPane9.setViewportView(txtK3);

        txtE3.setColumns(20);
        txtE3.setRows(5);
        jScrollPane10.setViewportView(txtE3);

        jLabel3.setText("Key Encrypt(K1)");

        jLabel4.setText("Cipher(E1) = En(M1)+K1");

        jLabel5.setText("Message(M2):");

        jLabel6.setText("Message(N1) = E1+ M2");

        jLabel7.setText("Message Hash (H2):");

        jLabel8.setText("Message (M3):");

        jLabel9.setText("Message(N2) = N1 + H2 + M3:");

        jLabel10.setText("Key Encrypt(K3):");

        jLabel11.setText("Cipher(E3) = En(N2)+K3");

        btnMaHoaM1.setText("Mã hóa M1");
        btnMaHoaM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaM1ActionPerformed(evt);
            }
        });

        btnNoiChuoiN1.setText("Nối chuỗi N1");
        btnNoiChuoiN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoiChuoiN1ActionPerformed(evt);
            }
        });

        btnBamChuoiN1.setText("Băm chuỗi N1");
        btnBamChuoiN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBamChuoiN1ActionPerformed(evt);
            }
        });

        btnNoiChuoiN2.setText("Nối chuỗi N2");
        btnNoiChuoiN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoiChuoiN2ActionPerformed(evt);
            }
        });

        btnMaHoaN2.setText("Mã hóa N2");
        btnMaHoaN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaN2ActionPerformed(evt);
            }
        });

        btnLuuFile.setText("Lưu File");
        btnLuuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBamChuoiN1)
                                    .addComponent(btnNoiChuoiN1)
                                    .addComponent(btnNoiChuoiN2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMaHoaN2)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMaHoaM1)
                                .addGap(14, 14, 14)))))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(btnLuuFile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnMaHoaM1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnNoiChuoiN1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnBamChuoiN1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(btnNoiChuoiN2)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(btnMaHoaN2)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLuuFile)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaHoaM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaM1ActionPerformed
        // TODO add your handling code here:
        try{
            myEncryptionKey= txtK1.getText();
            myEncryptionScheme = DESEDE_ENCRYPTION_SCHEME;
            keyAsBytes = myEncryptionKey.getBytes(UNICODE_FORMAT);
            myKeySpec = new DESedeKeySpec(keyAsBytes);
            mySecretKeyFactory = SecretKeyFactory.getInstance(myEncryptionScheme);
            cipher = Cipher.getInstance(myEncryptionScheme);
            key = mySecretKeyFactory.generateSecret(myKeySpec);
            System.out.println("khoa ma hoa k: "+ " "+ key);
            String plainText=txtM1.getText();
            String encrypted = encrypt(plainText);
            System.out.println("Encrypted value:"+encrypted);
            txtE1.setText(encrypted); 
        }catch(Exception e){
            System.out.println("da ma hoa van ban" +e);
        }
    }//GEN-LAST:event_btnMaHoaM1ActionPerformed

    public String encrypt (String unencryptedString){
        String encryptedString = null;
        try{
            cipher.init(Cipher.ENCRYPT_MODE,key);
            byte[] plainText=unencryptedString.getBytes(UNICODE_FORMAT);
            byte[] encryptedText=cipher.doFinal(plainText);
          //  BASE64Encoder base64encoder=new BASE64Encoder();
            encryptedString= Base64.getEncoder().encodeToString(encryptedText);
            
        }catch(Exception e){
            e.printStackTrace();
        }
        return encryptedString;
    }
    private void btnBamChuoiN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBamChuoiN1ActionPerformed
        // TODO add your handling code here:
        try {

            String pass = txtN1.getText();
            String bam = "";
            bam =  pass;
            MessageDigest md = MessageDigest.getInstance("MD5");
            md.update(bam.getBytes());
            byte[] byteData = md.digest();
            StringBuffer sb = new StringBuffer();
            for (int i = 0; i < byteData.length; i++) {
                sb.append(Integer.toString((byteData[i] & 0xff) + 0x100, 16).substring(1));
            }
            System.out.println("Digest (int hex format):: " + sb.toString());
            txtH2.setText(sb.toString());
            StringBuffer hexString = new StringBuffer();
            for (int i = 0; i < byteData.length; i++) {
                String hex = Integer.toHexString(0xff & byteData[i]);
                if (hex.length() == 1) {
                    hexString.append('0');
                }
                hexString.append(hex);
            }
            System.out.println("Digest(in hex format) :: " + hexString.toString());
        


            BufferedWriter bw = null;
            String fileName = "D:\\BamMD5.txt";
            bw = new BufferedWriter(new FileWriter(fileName));
            bw.write(hexString.toString());
            bw.close();
            JOptionPane.showMessageDialog(null, "Bam thanh cong!!");
        } catch (Exception ex) {
            System.out.println("loi : " + ex);
        }
        
    }//GEN-LAST:event_btnBamChuoiN1ActionPerformed

    private void btnNoiChuoiN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoiChuoiN1ActionPerformed
        // TODO add your handling code here:
        String a = "" ;
        String user = txtM2.getText();
        String pass = txtE1.getText();
        a =  pass+user;
        txtN1.setText(a);
    }//GEN-LAST:event_btnNoiChuoiN1ActionPerformed

    private void btnNoiChuoiN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoiChuoiN2ActionPerformed
        // TODO add your handling code here:
        String a = "" ;
        String user = txtN1.getText();
        String pass = txtH2.getText();
        String conlai = txtM3.getText();
        a = user + pass + conlai;
        txtN2.setText(a);
    }//GEN-LAST:event_btnNoiChuoiN2ActionPerformed

     
    
    private void btnMaHoaN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaN2ActionPerformed
        // TODO add your handling code here:
        String plainText = txtN2.getText();
        int i, j, r, s;
        String result = "";
        r = Integer.parseInt(txtK3.getText());//r là khóa củng là số hàng của màng
        //tính số cột của mảng
        if (plainText.length() % r == 0) {
            s = plainText.length() / r;
        } else {
            s = (plainText.length() / r) + 1;
        }
        //s = 2 * (plainText.length() / r); //tính chiều dài của mảng
        char ct[][] = new char[r][s];

        for (i = 0; i < r; i++) {
            int t = i;
            for (j = 0; j < s; j++) {
                ct[i][j] = plainText.charAt(t);
                t = t + r;
                if (t > plainText.length() - 1) {
                    break;
                }
            }
        }
//      lấy chuỗi trong mảng ra
        for (i = 0; i < r; i++) {
            for (j = 0; j < s; j++) {
                char d = ct[i][j];
                if (d == '\0') {
                    continue;
                } else {
                    result = result + ct[i][j];
                }
            }
        }
        txtE3.setText(result);
    }//GEN-LAST:event_btnMaHoaN2ActionPerformed

    private void btnLuuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuFileActionPerformed
        // TODO add your handling code here:
        try {
            BufferedWriter bw1 = null;
            BufferedWriter bw2 = null;
            String fileName1 = "D:\\LuuE3.txt";
            bw1 = new BufferedWriter(new FileWriter(fileName1));     
            String s1 = txtE3.getText();
            bw1 = new BufferedWriter(new FileWriter(fileName1));
            bw1.write(s1);
            
            String fileName2 = "D:\\LuuK3.txt";
            bw2 = new BufferedWriter(new FileWriter(fileName2));     
            String s2 = txtK3.getText();
            bw2 = new BufferedWriter(new FileWriter(fileName2));
            bw2.write(s2);
            
            bw1.close();            
            bw2.close();
            JOptionPane.showMessageDialog(null, "Luu file thanh cong !!");
        } catch (Exception e) {
        }

            
        
    }//GEN-LAST:event_btnLuuFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEncrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEncrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEncrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEncrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEncrypt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBamChuoiN1;
    private javax.swing.JButton btnLuuFile;
    private javax.swing.JButton btnMaHoaM1;
    private javax.swing.JButton btnMaHoaN2;
    private javax.swing.JButton btnNoiChuoiN1;
    private javax.swing.JButton btnNoiChuoiN2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea txtE1;
    private javax.swing.JTextArea txtE3;
    private javax.swing.JTextArea txtH2;
    private javax.swing.JTextArea txtK1;
    private javax.swing.JTextArea txtK3;
    private javax.swing.JTextArea txtM1;
    private javax.swing.JTextArea txtM2;
    private javax.swing.JTextArea txtM3;
    private javax.swing.JTextArea txtN1;
    private javax.swing.JTextArea txtN2;
    // End of variables declaration//GEN-END:variables
}
